### ISSUE TITLE
untappd icon

### ISSUE THREAD

**Issue by nengard** [samcollins/css-social-buttons#29]
It would be cool if an untappd icon were added! Thanks for the awesome work on this.

Nicole

**Comment by zimbatm** [comment]
Hi,

I am closing all icon requests in an effort to keep this project clean. We unfortunately don't have the time to implement all the icon ourselves and it would be misleading to keep these issues open.

The good news is that I have also made icon contribution much easier (aka possible). There are the documented steps that you can follow if you would really like to see your icon included: https://github.com/samcollins/css-social-buttons#how-to-contribute . Please keep in mind that this icon set is for social icons.

Mistakes happen so if you feel that I have unjustly closed this issue please let me know.

Cheers,
zimbatm
