### ISSUE TITLE
Include 'Install Method' by Bower Package Manager

### ISSUE THREAD

**Issue by jcanfield** [samcollins/css-social-buttons#44]
After using the Social buttons in a couple recent projects and using Bower as a package manager to help me keep my Javascript and libraries organized, I believe that it would be nice to have Zocial included in the Bower Registry. 

All that is needed is a `components.json` file in the root of `samcollins/css-social-buttons` which would include:

```javascript
{
  "name": "Zocial",
  "version": "1.0.0",
  "main": ["./css/zocial.css"]
}
```

and then a simple command to register with Bower's Registry: `bower register zocial git://github.com/samcollins/css-social-buttons`.

Afterwords, adding a simple message to the `README.md` stating that you can also install (basically download) Zocial CSS Social Buttons via [Bower Package Manager](https://github.com/twitter/bower#readme).

Thanks for your hard work as well!

**Comment by zimbatm** [comment]
Added in 0edff886966cdfaa33260ca78f29848b6ac8eab9
