### ISSUE TITLE
Predefined link hover text color messing up buttons

### ISSUE THREAD

**Issue by sheabunge** [samcollins/css-social-buttons#51]
If I have a color set on the `a:hover` element **before** the zocial style rules take place, Zocial will not override this and instead use the previously defined color on hover.

For example, if I had this in my stylesheet:

    a:hover { color: orange; }

Hovering over a button with white text will change the text to orange. This looks very ugly, and so a default hover state color for a link will `.zocial` should be defined.

**Comment by zimbatm** [comment]
Thanks. Finally merged !
