### ISSUE TITLE
icon width resize

### ISSUE THREAD

**Issue by lepptin** [samcollins/css-social-buttons#64]
how can resize icon width ? 
I want to use facebook icon and I use this line of code
<a class="zocial icon twitter">Facebook</a>
but icon doesnt seem like in demo. It's bigger than demo one

**Comment by zimbatm** [comment]
It's hard to know without a reproducible code sample. Some other CSS might have been interfering.

The best way to detect what is interfering is to inspect the item using the web inspector. Then look at the CSS properties that set by other stylesheets and try to toggle them until it works.
