### ISSUE TITLE
How to add or update icons on font ?

### ISSUE THREAD

**Issue by pedrosanchezpernia** [samcollins/css-social-buttons#65]
Hello there, big fan of this library.
One year since the last commit, but the social landscape need a faster catch-up...
Is there a way for the community to update this repo with new providers or to update new logos (windows, for example) ?
As far as I know, the graph is encapsulated in the font, so maybe a tool / service font-related.
Thanks.

**Comment by zimbatm** [comment]
Hi, this has (finally!) been fixed in master.
