### ISSUE TITLE
Added to cdnjs

### ISSUE THREAD

**Issue by ecabuk** [samcollins/css-social-buttons#71]
http://cdnjs.com/libraries/zocial

**Comment by zimbatm** [comment]
How are releases managed on cdnjs ? I've just made a fresh v1.0.0 release.

**Comment by ecabuk** [comment]
They are not accepting manual submissions anymore, project should be compatible.

https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by dandv** [comment]
Would love to see the (latest) release on CDNJS.

**Comment by zimbatm** [comment]
anyone wants to contribute a package.json in a PR ?

**Comment by zimbatm** [comment]
Alright, here is a PR: #84 anyone wants to review ?

**Comment by zimbatm** [comment]
https://cdnjs.com/libraries/css-social-buttons ! thanks to @PeterDaveHello

**Comment by PeterDaveHello** [comment]
:+1:
