### ISSUE TITLE
Malformed bower.json

### ISSUE THREAD

**Issue by SabreCat** [samcollins/css-social-buttons#87]
Builds of this library using bower are failing with `EMALFORMED` errors.

I suspect it's this line: https://github.com/samcollins/css-social-buttons/blob/master/bower.json#L13. There's an extra comma in the array, leading to an `Unexpected token ]` error.

**Comment by zimbatm** [comment]
Thanks !

**Comment by SabreCat** [comment]
Awesome. However, it appears that new builds will not include the fix unless the version tag is updated: http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/#updatingandmaintenance

**Comment by zimbatm** [comment]
Alright. Released v1.1.1 just for you
